const SET_USER_DETAILS = 'SET_USER_DETAILS';
const SET_MENU_ITEMS = 'SET_MENU_ITEMS'
const SET_MESSAGE_DETAILS = 'SET_MESSAGE_DETAILS'

export const ActionTypes = {
    SET_USER_DETAILS,
    SET_MENU_ITEMS,
    SET_MESSAGE_DETAILS
}